News/urls.py
# ruff: noqa: E501
from django.urls import path
from News.views import (
                        createNews,
                        updateNews,
                        authorsListNews,
                        deleteNews,
                        send_mail_to_all,
                        home_view,
                        read_news
                        )

urlpatterns = [
    path('authors_news/', authorsListNews, name="authors_news"),

    #path('home', , name='home')
    path('create_news/', createNews, name="create_news"),
    path('update_news/<int:pk>/', updateNews, name="update_news"),
    path('delete_news/<int:pk>/', deleteNews, name="delete_news"),
    path('send_mail/', send_mail_to_all, name="send_mail"),
    path('home/', home_view, name="home"),
    path('read_news/<int:pk>', read_news, name="read_news")
]

'''
    path('add-blog/', add_blog, name="add_blog"),
    path('blog-delete/<id>', blog_delete, name="blog_delete"),
    path('blog-update/<slug>/', blog_update, name="blog_update"),
'''

NewsProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("News.urls", "News"), namespace="news")),
    path('auth/', include(('user_auth.urls', "user_auth"), namespace="auth")),
    path('summernote/', include('django_summernote.urls')),
    path('places/', include(('remarkable_places.urls',"remarkable_places"), namespace="places"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

remarkable_places/urls.py
from django.urls import path
from remarkable_places.views import (fetch_data_for_all_districts,
                                    get_all_places,
                                    export_weather_summary_to_xlsx)

urlpatterns = [
    path('get_meteo/', fetch_data_for_all_districts, name='get_meteo'),
    path('get_places/', get_all_places, name='get_all_places'),
    path('export-weather-summary/', export_weather_summary_to_xlsx, name='export_weather_summary'),
]

remarkable_places/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django_admin_geomap import GeoItem

class RemarkablePlace(models.Model, GeoItem):

    name = models.CharField(max_length=255, unique=True) 
    lon = models.FloatField()  # долгота
    lat = models.FloatField()  # широта
    rating = models.PositiveIntegerField( 
        default=3,
        validators=[MinValueValidator(0), MaxValueValidator(25)]
    )

    @property
    def geomap_longitude(self):
        return '' if self.lon is None else str(self.lon)

    @property
    def geomap_latitude(self):
        return '' if self.lat is None else str(self.lat)


    def __str__(self):
        return self.name

class WeatherSummary(models.Model):

    temperature = models.FloatField(help_text="Температура в градусах Цельсия")
    humidity = models.IntegerField(help_text="Влажность воздуха в процентах")
    pressure = models.IntegerField(help_text="Атмосферное давление в мм ртутного столба")
    wind_direction = models.CharField(max_length=50, help_text="Направление ветра")
    wind_speed = models.FloatField(help_text="Скорость ветра в м/с")
    timestamp = models.DateTimeField(auto_now_add=True, help_text="Дата и время записи")
    remarkable_place = models.ForeignKey(RemarkablePlace, on_delete=models.CASCADE)

    def __str__(self):
        return f"Weather on {self.timestamp}: {self.temperature}°C, {self.wind_speed} m/s"
    

remarkable_places/forms.py
from django import forms
from .models import RemarkablePlace
from django.forms.models import ModelChoiceField

class XlsxImportForm(forms.Form):
    xlsx_file = forms.FileField()

class DateRangeForm(forms.Form):
    remarkable_place = forms.ChoiceField(choices=ModelChoiceField(queryset=RemarkablePlace.objects.all()))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

remarkable_places/views.py
from django.shortcuts import render
from NewsProject.tasks import fetch_data_for_district
from remarkable_places.models import RemarkablePlace
from remarkable_places.models import WeatherSummary
from django.http import JsonResponse
from openpyxl import Workbook
from django.http import HttpResponse
from datetime import datetime
from .forms import DateRangeForm
# Create your views here.

def fetch_data_for_all_districts(request):
    # Получаем все районы
    districts = RemarkablePlace.objects.all()
    
    # Запускаем задачу для каждого района
    for district in districts:
        fetch_data_for_district.delay(district.id)
    
    return JsonResponse({'status': 'tasks are being processed'})

def get_all_places(request):

    remarkable_places = RemarkablePlace.objects.all()
    form = DateRangeForm(request.GET)

    context = {
        'remarkable_places': remarkable_places,
        'form': form,
    }
    
    return render(request, 'remarkable_places/places_info.html', context)


def export_weather_summary_to_xlsx(request):
    form = DateRangeForm(request.GET)
    
    if request.method == 'GET' and form.is_valid():

        remarkable_place = form.cleaned_data['remarkable_place']
        place_name = remarkable_place.name
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        
        weather_summaries = WeatherSummary.objects.filter(
            remarkable_place__name=place_name,
            timestamp__range=[start_date, end_date]
        )

        wb = Workbook()
        ws = wb.active
        ws.title = "Weather Summary"

        ws.append(['Примечательное место', 'Дата', 'Температура', 'Влажность', 'Скорость ветра'])

        for summary in weather_summaries:
            ws.append([
                summary.remarkable_place.name,
                summary.timestamp.replace(tzinfo=None),
                summary.temperature,
                summary.humidity,
                summary.wind_speed
            ])

        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"weather_summary_{timestamp}.xlsx"
        response['Content-Disposition'] = f'attachment; filename="{filename}"'

        wb.save(response)

        return response

    return render(request, 'remarkable_places/places_info.html', {'form': form})

templates/remarkable_places/add_records_form.html
{% extends 'admin/base_site.html' %}

{% block content %}
    <div>
        <form action="." method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Импортировать из XLSX">
        </form>
    </div>
    <br />
{% endblock %}

templates/remarkable_places/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- Основные стили, которые будут общими для всех страниц -->

    <link rel="stylesheet" href="{% static 'News/css/base.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">

    {% block extra_styles %}
    {% endblock %}
</head>
<body>


<header class="header">
  <div class = "header-container">
    <a href class="logo"><h1>Places</h1></a>
    <nav class="nav-list">
        <ul>
            <li><a href="{% url 'News:home' %}">Новости</a></li>
            <li><a href="{% url 'remarkable_places:get_all_places' %}">Сводки погоды</a></li>
            {% if user.is_authenticated %}<li><a href="{% url 'News:authors_news' %}">Мои посты</a></li>{% endif %}
        </ul>
    </nav>
    {% if user.is_authenticated %}
      <a class="auth_btn" href="{% url 'user_auth:logout' %}">
          Выход
      </a>
    {% else %}
      <a class="auth_btn" href="{% url 'user_auth:login' %}">Войти</a>
    {% endif %}
  </div>
</header>

<div class="content">
    {% block content %}
    {% endblock %}
</div>

<footer>
      <span>
        © 2025 Все права не защищены.
      </span>
</footer>

</body>
</html>

templates/remarkable_places/places_info.html
{% extends "remarkable_places/base.html" %}
{% load static %}

{% block extra_styles %}
<!-- Дополнительные стили для этой страницы -->
<link rel="stylesheet" href="{% static 'News/css/home.css' %}">
{% endblock %}

{% block content %}
<div class="form-container">
    <form class="xl_form" method="get" action="{% url 'remarkable_places:export_weather_summary' %}">
        {% csrf_token %}
        <div>
            <label for="remarkable_place">Место</label>
            {{ form.remarkable_place.name }}
        </div>

        <div>
            <label for="start_date">Нижняя граница</label>
            {{ form.start_date }}
        </div>

        <div>
            <label for="end_date">Верхняя граница</label>
            {{ form.end_date }}
        </div>
        <button type="submit">Экспортировать</button>
    </form>
</div>

    <div class="news-container">
    {% for place in remarkable_places %}
        <div class="separate-elem">
            <div class = "place-wrapper">
                <strong>Место:</strong> {{ place.name }}<br>
                <strong>Рейтинг:</strong> {{ place.rating }} / 25<br>
            </div>
            <div class = "news-text-content">

            {% with first_weather=place.weathersummary_set.first %}

                {% if first_weather %}
                <div>
                    <strong>-Краткая сводка-</strong><br>
                    <strong>Температура:</strong> {{ first_weather.temperature }}°C<br>
                    <strong>Влажность:</strong> {{ first_weather.humidity }}%<br>
                    <strong>Направление ветра:</strong> {{ first_weather.wind_direction }}<br>
                    <strong>Скорость ветра:</strong> {{ first_weather.wind_speed }} м/с<br>
                </div>
                {% else %}
                    <strong>Нет доступной сводки погоды для этого места</strong><br>
                {% endif %}
            {% endwith %}
            </div>
        </div>

    {% endfor %}
    </div>

{% endblock %}

templates/remarkable_places/record_change_list.html
{% extends 'admin/change_list.html' %}
{% load admin_list %}

{% block object-tools-items %}
    <li>
        <a href="import-records-from-xlsx/" class="addlink">Импортировать записи из XLSX</a>
    </li>
    {% change_list_object_tools %}
{% endblock %}